from os.path import dirname, abspath, join

paths = {
    "about"                 :       r"icons\about.png",
    "accept"                :       r"icons\accept.png",
    "add"                   :       r"icons\add.png",
    "advance_transaction"   :       r"icons\advance_transaction.png",
    "back"                  :       r"icons\back.png",
    "bonus_transaction"     :       r"icons\bonus_transaction.png",
    "business_information"  :       r"icons\business_information.png",
    "calendar"              :       r"icons\calendar.png",
    "cancel"                :       r"icons\cancel.png",
    "check_connection"      :       r"icons\check_connection.png",
    "clear_all"             :       r"icons\clear_all.png",
    "close_1"               :       r"icons\close_1.png",
    "close_2"               :       r"icons\close_2.png",
    "complete"              :       r"icons\complete.png",
    "confirm_password"      :       r"icons\confirm_password.png",
    "cross_mark_1"          :       r"icons\cross_mark_1.png",
    "cross_mark_2"          :       r"icons\cross_mark_2.png",
    "cross_mark_3"          :       r"icons\cross_mark_3.png",
    "decline"               :       r"icons\decline.png",
    "dismissal"             :       r"icons\dismissal.png",
    "down_arrow"            :       r"icons\down_arrow.png",
    "email_1"               :       r"icons\email_1.png",
    "email_2"               :       r"icons\email_2.png",
    "employment"            :       r"icons\employment.png",
    "event"                 :       r"icons\event.png",
    "event_green"           :       r"icons\event_green.png",
    "event_name"            :       r"icons\event_name.png",
    "expand_1"              :       r"icons\expand_1.png",
    "expand_2"              :       r"icons\expand_2.png",
    "general"               :       r"icons\general.png",
    "get_message"           :       r"icons\get_message.png",
    "green_dot"             :       r"icons\green_dot.png",
    "group"                 :       r"icons\group.png",
    "hint_icon"             :       r"icons\hint_icon.png",
    "hiring"                :       r"icons\hiring.png",
    "home"                  :       r"icons\home.png",
    "info"                  :       r"icons\info.png",
    "item"                  :       r"icons\item.png",
    "left_arrow"            :       r"icons\left_arrow.png",
    "login_btn"             :       r"icons\login_btn.png",
    "login_header"          :       r"icons\login_header.png",
    "mail"                  :       r"icons\mail.png",
    "management_system_1"   :       r"icons\management_system_1.png",
    "management_system_2"   :       r"icons\management_system_2.png",
    "messages_1"            :       r"icons\messages_1.png",
    "messages_2"            :       r"icons\messages_2.png",
    "money_green"           :       r"icons\money_green.png",
    "mop"                   :       r"icons\mop.png",
    "next"                  :       r"icons\next.png",
    "passcode"              :       r"icons\passcode.png",
    "password"              :       r"icons\password.png",
    "pay_back"              :       r"icons\pay_back.png",
    "pending"               :       r"icons\pending.png",
    "permission"            :       r"icons\permission.png",
    "personal_information"  :       r"icons\personal_information.png",
    "phone_book"            :       r"icons\phone_book.png",
    "plan"                  :       r"icons\plan.png",
    "profile_1"             :       r"icons\profile_1.png",
    "profile_2"             :       r"icons\profile_2.png",
    "reconnect"             :       r"icons\reconnect.png",
    "red_dot"               :       r"icons\red_dot.png",
    "reload"                :       r"icons\reload.png",
    "resend"                :       r"icons\resend.png",
    "reset_password_1"      :       r"icons\reset_password_1.png",
    "reset_password_2"      :       r"icons\reset_password_2.png",
    "restart"               :       r"icons\restart.png",
    "right_arrow_1"         :       r"icons\right_arrow_1.png",
    "right_arrow_2"         :       r"icons\right_arrow_2.png",
    "salary_adjustment"     :       r"icons\salary_adjustment.png",
    "search"                :       r"icons\search.png",
    "security"              :       r"icons\security.png",
    "select_1"              :       r"icons\select_1.png",
    "select_2"              :       r"icons\select_2.png",
    "select_3"              :       r"icons\select_3.png",
    "send_code_1"           :       r"icons\send_code_1.png",
    "send_code_2"           :       r"icons\send_code_2.png",
    "send_code_3"           :       r"icons\send_code_3.png",
    "send_code_4"           :       r"icons\send_code_4.png",
    "send_message"          :       r"icons\send_message.png",
    "sign_out"              :       r"icons\sign_out.png",
    "statistics"            :       r"icons\statistics.png",
    "swap"                  :       r"icons\swap.png",
    "timer"                 :       r"icons\timer.png",
    "transactions"          :       r"icons\transactions.png",
    "up_arrow"              :       r"icons\up_arrow.png",
    "view"                  :       r"icons\view.png",
    "view_employees"        :       r"icons\view_employees.png",
    "white_dot"             :       r"icons\white_dot.png"
}

def getPath(name:str) -> str:
    try:
        current_directory = dirname(abspath(__file__))
        return join(current_directory, paths[name])
    except:
        # For avoiding the entire program from crashing in
        # case of an error while creating paths for icons
        return ""