# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from package import icons_rc


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 496)
        MainWindow.setMinimumSize(QtCore.QSize(550, 496))
        MainWindow.setWindowIcon(QtGui.QIcon(":/newSource/icons/management_system_2.png"))
        MainWindow.setStyleSheet("QMenuBar {\n"
"    background-color:#555555;\n"
"    color:#FFFFFF\n"
"}\n"
"\n"
"QMenuBar:item::selected {\n"
"    background-color: #be8af9;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color:#555555;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background-color: #555555;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QMenu::item::hover {\n"
"    background-color: #be8af9;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #be8af9;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"background-color:#242424;\n"
"height:1px;\n"
"margin:0px;\n"
"}\n"
"\n"
"QMenu[objectName=\"menuForm\"]::separator {\n"
"background-color:#000000;\n"
"height:1px;\n"
"margin:5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color:#191919;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_sub_bar = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_sub_bar.setMinimumSize(QtCore.QSize(421, 40))
        self.widget_sub_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_sub_bar.setStyleSheet("QLabel[objectName=\"lbl_connection_status\"]{\n"
"    color:#f0f0f0;\n"
"    font-size:10px;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_contact_msg\"]{\n"
"    color:#f0f0f0;\n"
"    font-size:10px;\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_contact_back\"]{\n"
"    background-color:None;\n"
"    border:None;\n"
"    color:#be8af9;\n"
"    font-size:10px;\n"
"}")
        self.widget_sub_bar.setObjectName("widget_sub_bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_sub_bar)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_connection_icon = QtWidgets.QLabel(parent=self.widget_sub_bar)
        self.lbl_connection_icon.setMinimumSize(QtCore.QSize(20, 10))
        self.lbl_connection_icon.setMaximumSize(QtCore.QSize(20, 10))
        self.lbl_connection_icon.setText("")
        self.lbl_connection_icon.setPixmap(QtGui.QPixmap(":/newSource/icons/red_dot.png"))
        self.lbl_connection_icon.setScaledContents(True)
        self.lbl_connection_icon.setObjectName("lbl_connection_icon")
        self.horizontalLayout_4.addWidget(self.lbl_connection_icon)
        self.lbl_connection_status = QtWidgets.QLabel(parent=self.widget_sub_bar)
        self.lbl_connection_status.setMinimumSize(QtCore.QSize(160, 16))
        self.lbl_connection_status.setMaximumSize(QtCore.QSize(160, 16))
        self.lbl_connection_status.setObjectName("lbl_connection_status")
        self.horizontalLayout_4.addWidget(self.lbl_connection_status)
        spacerItem = QtWidgets.QSpacerItem(289, 19, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lbl_contact_msg = QtWidgets.QLabel(parent=self.widget_sub_bar)
        self.lbl_contact_msg.setMinimumSize(QtCore.QSize(176, 21))
        self.lbl_contact_msg.setMaximumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(1) # Was -1
        self.lbl_contact_msg.setFont(font)
        self.lbl_contact_msg.setWordWrap(True)
        self.lbl_contact_msg.setObjectName("lbl_contact_msg")
        self.horizontalLayout_4.addWidget(self.lbl_contact_msg)
        self.btn_contact_back = QtWidgets.QPushButton(parent=self.widget_sub_bar)
        self.btn_contact_back.setMinimumSize(QtCore.QSize(54, 21))
        self.btn_contact_back.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setPointSize(1) # Was -1
        self.btn_contact_back.setFont(font)
        self.btn_contact_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_contact_back.setIconSize(QtCore.QSize(20, 24))
        self.btn_contact_back.setObjectName("btn_contact_back")
        self.horizontalLayout_4.addWidget(self.btn_contact_back)
        self.gridLayout_2.addWidget(self.widget_sub_bar, 1, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("QLabel {\n"
"    color:#f0f0f0;\n"
"    font-size:18px;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_header_message\"] {\n"
"    color:#f0f0f0;\n"
"    font-size:12px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.gridLayout = QtWidgets.QGridLayout(self.page_login)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_header_page_login = QtWidgets.QWidget(parent=self.page_login)
        self.widget_header_page_login.setMinimumSize(QtCore.QSize(459, 68))
        self.widget_header_page_login.setMaximumSize(QtCore.QSize(16777215, 68))
        self.widget_header_page_login.setStyleSheet("QLabel[objectName=\"lbl_welcome\"] {\n"
"    color:#f0f0f0;\n"
"    background-color:#191919;\n"
"    font-size:18px;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_welcome_msg\"] {\n"
"    color:#f0f0f0;\n"
"    background-color:#191919;\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color:#191919;\n"
"}")
        self.widget_header_page_login.setObjectName("widget_header_page_login")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_header_page_login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_welcome = QtWidgets.QLabel(parent=self.widget_header_page_login)
        self.lbl_welcome.setObjectName("lbl_welcome")
        self.verticalLayout.addWidget(self.lbl_welcome)
        self.lbl_welcome_msg = QtWidgets.QLabel(parent=self.widget_header_page_login)
        self.lbl_welcome_msg.setObjectName("lbl_welcome_msg")
        self.verticalLayout.addWidget(self.lbl_welcome_msg)
        self.gridLayout.addWidget(self.widget_header_page_login, 0, 0, 1, 1)
        self.widget_page_login_container = QtWidgets.QWidget(parent=self.page_login)
        self.widget_page_login_container.setStyleSheet("QWidget {\n"
"    background-color:#242424;\n"
"    border:1px solid #242424;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color:#f0f0f0;\n"
"    font-size:18px;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_forgot_password\"]{\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_mail_address_login_page\"]{\n"
"    font-size:11px;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_password_login_page\"]{\n"
"    font-size:11px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border:2px solid #555555;\n"
"    border-radius:10px;\n"
"    background-color:#555555;\n"
"    color:#f0f0f0;\n"
"    padding-left:8px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border:1px solid #be8af9;\n"
"    border-radius:10px;\n"
"    background-color:#555555;\n"
"    background\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:#be8af9;\n"
"    color:#1b0038;\n"
"    border:2px solid #be8af9;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color:#f0f0f0;\n"
"    color:#000000;\n"
"    border:2px solid #f0f0f0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color:#808080;\n"
"    color:#000000;\n"
"    border:2px solid #808080;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_forgot_password\"]{\n"
"    background-color:#242424;\n"
"    border:None;\n"
"    color:#be8af9;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color:#f0f0f0;\n"
"}")
        self.widget_page_login_container.setObjectName("widget_page_login_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_page_login_container)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.widget_page_login_header = QtWidgets.QWidget(parent=self.widget_page_login_container)
        self.widget_page_login_header.setMinimumSize(QtCore.QSize(441, 61))
        self.widget_page_login_header.setMaximumSize(QtCore.QSize(16777215, 61))
        self.widget_page_login_header.setObjectName("widget_page_login_header")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_page_login_header)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(129, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.lbl_login_icon = QtWidgets.QLabel(parent=self.widget_page_login_header)
        self.lbl_login_icon.setMinimumSize(QtCore.QSize(60, 50))
        self.lbl_login_icon.setMaximumSize(QtCore.QSize(60, 50))
        self.lbl_login_icon.setText("")
        self.lbl_login_icon.setPixmap(QtGui.QPixmap(":/newSource/icons/login_header.png"))
        self.lbl_login_icon.setScaledContents(True)
        self.lbl_login_icon.setObjectName("lbl_login_icon")
        self.horizontalLayout_6.addWidget(self.lbl_login_icon)
        self.lbl_login = QtWidgets.QLabel(parent=self.widget_page_login_header)
        self.lbl_login.setMinimumSize(QtCore.QSize(60, 31))
        self.lbl_login.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(1) # Was -1
        self.lbl_login.setFont(font)
        self.lbl_login.setObjectName("lbl_login")
        self.horizontalLayout_6.addWidget(self.lbl_login)
        spacerItem3 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.widget_page_login_header)
        spacerItem4 = QtWidgets.QSpacerItem(20, 90, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.lbl_mail_address_login_page = QtWidgets.QLabel(parent=self.widget_page_login_container)
        self.lbl_mail_address_login_page.setMinimumSize(QtCore.QSize(341, 16))
        self.lbl_mail_address_login_page.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbl_mail_address_login_page.setObjectName("lbl_mail_address_login_page")
        self.verticalLayout_2.addWidget(self.lbl_mail_address_login_page)
        self.widget_page_login_mail = QtWidgets.QWidget(parent=self.widget_page_login_container)
        self.widget_page_login_mail.setMinimumSize(QtCore.QSize(406, 40))
        self.widget_page_login_mail.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_page_login_mail.setObjectName("widget_page_login_mail")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_page_login_mail)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_email_icon_login_page = QtWidgets.QLabel(parent=self.widget_page_login_mail)
        self.lbl_email_icon_login_page.setMinimumSize(QtCore.QSize(31, 31))
        self.lbl_email_icon_login_page.setMaximumSize(QtCore.QSize(31, 31))
        self.lbl_email_icon_login_page.setText("")
        self.lbl_email_icon_login_page.setPixmap(QtGui.QPixmap(":/newSource/icons/email_1.png"))
        self.lbl_email_icon_login_page.setScaledContents(True)
        self.lbl_email_icon_login_page.setObjectName("lbl_email_icon_login_page")
        self.horizontalLayout.addWidget(self.lbl_email_icon_login_page)
        self.lineEdit_email_page_login = QtWidgets.QLineEdit(parent=self.widget_page_login_mail)
        self.lineEdit_email_page_login.setMinimumSize(QtCore.QSize(351, 31))
        self.lineEdit_email_page_login.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lineEdit_email_page_login.setClearButtonEnabled(True)
        self.lineEdit_email_page_login.setObjectName("lineEdit_email_page_login")
        self.horizontalLayout.addWidget(self.lineEdit_email_page_login)
        self.verticalLayout_2.addWidget(self.widget_page_login_mail)
        self.lbl_password_login_page = QtWidgets.QLabel(parent=self.widget_page_login_container)
        self.lbl_password_login_page.setMinimumSize(QtCore.QSize(341, 16))
        self.lbl_password_login_page.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbl_password_login_page.setObjectName("lbl_password_login_page")
        self.verticalLayout_2.addWidget(self.lbl_password_login_page)
        self.widget_page_login_password = QtWidgets.QWidget(parent=self.widget_page_login_container)
        self.widget_page_login_password.setMinimumSize(QtCore.QSize(406, 40))
        self.widget_page_login_password.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_page_login_password.setObjectName("widget_page_login_password")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_page_login_password)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_password_icon_page_login = QtWidgets.QLabel(parent=self.widget_page_login_password)
        self.lbl_password_icon_page_login.setMinimumSize(QtCore.QSize(31, 31))
        self.lbl_password_icon_page_login.setMaximumSize(QtCore.QSize(31, 31))
        self.lbl_password_icon_page_login.setText("")
        self.lbl_password_icon_page_login.setPixmap(QtGui.QPixmap(":/newSource/icons/password.png"))
        self.lbl_password_icon_page_login.setScaledContents(True)
        self.lbl_password_icon_page_login.setObjectName("lbl_password_icon_page_login")
        self.horizontalLayout_2.addWidget(self.lbl_password_icon_page_login)
        self.lineEdit_password_page_login = QtWidgets.QLineEdit(parent=self.widget_page_login_password)
        self.lineEdit_password_page_login.setMinimumSize(QtCore.QSize(351, 31))
        self.lineEdit_password_page_login.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lineEdit_password_page_login.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password_page_login.setClearButtonEnabled(True)
        self.lineEdit_password_page_login.setObjectName("lineEdit_password_page_login")
        self.horizontalLayout_2.addWidget(self.lineEdit_password_page_login)
        self.verticalLayout_2.addWidget(self.widget_page_login_password)
        self.widget_page_login_sub_bar = QtWidgets.QWidget(parent=self.widget_page_login_container)
        self.widget_page_login_sub_bar.setMinimumSize(QtCore.QSize(406, 40))
        self.widget_page_login_sub_bar.setObjectName("widget_page_login_sub_bar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_page_login_sub_bar)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_show_password_page_login = QtWidgets.QCheckBox(parent=self.widget_page_login_sub_bar)
        self.checkBox_show_password_page_login.setMinimumSize(QtCore.QSize(101, 17))
        self.checkBox_show_password_page_login.setObjectName("checkBox_show_password_page_login")
        self.horizontalLayout_3.addWidget(self.checkBox_show_password_page_login)
        spacerItem5 = QtWidgets.QSpacerItem(189, 19, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.btn_login = QtWidgets.QPushButton(parent=self.widget_page_login_sub_bar)
        self.btn_login.setMinimumSize(QtCore.QSize(91, 31))
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newSource/icons/login_btn.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_login.setIcon(icon)
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout_3.addWidget(self.btn_login)
        self.verticalLayout_2.addWidget(self.widget_page_login_sub_bar)
        self.widget_forgot_container = QtWidgets.QWidget(parent=self.widget_page_login_container)
        self.widget_forgot_container.setMinimumSize(QtCore.QSize(401, 40))
        self.widget_forgot_container.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_forgot_container.setObjectName("widget_forgot_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_forgot_container)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(84, 19, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.lbl_forgot_password = QtWidgets.QLabel(parent=self.widget_forgot_container)
        self.lbl_forgot_password.setMinimumSize(QtCore.QSize(131, 21))
        self.lbl_forgot_password.setMaximumSize(QtCore.QSize(0, 21))
        self.lbl_forgot_password.setObjectName("lbl_forgot_password")
        self.horizontalLayout_5.addWidget(self.lbl_forgot_password)
        self.btn_forgot_password = QtWidgets.QPushButton(parent=self.widget_forgot_container)
        self.btn_forgot_password.setMinimumSize(QtCore.QSize(61, 21))
        self.btn_forgot_password.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_forgot_password.setFont(font)
        self.btn_forgot_password.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_forgot_password.setIconSize(QtCore.QSize(20, 24))
        self.btn_forgot_password.setObjectName("btn_forgot_password")
        self.horizontalLayout_5.addWidget(self.btn_forgot_password)
        spacerItem7 = QtWidgets.QSpacerItem(96, 19, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_2.addWidget(self.widget_forgot_container)
        self.gridLayout.addWidget(self.widget_page_login_container, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_login)
        self.page_reset_password = QtWidgets.QWidget()
        self.page_reset_password.setObjectName("page_reset_password")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_reset_password)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_header_page_reset_password = QtWidgets.QWidget(parent=self.page_reset_password)
        self.widget_header_page_reset_password.setMinimumSize(QtCore.QSize(520, 68))
        self.widget_header_page_reset_password.setMaximumSize(QtCore.QSize(16777215, 68))
        self.widget_header_page_reset_password.setObjectName("widget_header_page_reset_password")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_header_page_reset_password)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_inner_header_reset_password = QtWidgets.QWidget(parent=self.widget_header_page_reset_password)
        self.widget_inner_header_reset_password.setMinimumSize(QtCore.QSize(441, 61))
        self.widget_inner_header_reset_password.setMaximumSize(QtCore.QSize(16777215, 61))
        self.widget_inner_header_reset_password.setObjectName("widget_inner_header_reset_password")
        self.widget_header_inner_header_reset_password = QtWidgets.QWidget(parent=self.widget_inner_header_reset_password)
        self.widget_header_inner_header_reset_password.setGeometry(QtCore.QRect(0, -10, 501, 42))
        self.widget_header_inner_header_reset_password.setMinimumSize(QtCore.QSize(0, 42))
        self.widget_header_inner_header_reset_password.setMaximumSize(QtCore.QSize(16777215, 42))
        self.widget_header_inner_header_reset_password.setObjectName("widget_header_inner_header_reset_password")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_header_inner_header_reset_password)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(139, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.lbl_reset_password_icon = QtWidgets.QLabel(parent=self.widget_header_inner_header_reset_password)
        self.lbl_reset_password_icon.setMinimumSize(QtCore.QSize(40, 18))
        self.lbl_reset_password_icon.setMaximumSize(QtCore.QSize(50, 22))
        self.lbl_reset_password_icon.setText("")
        self.lbl_reset_password_icon.setPixmap(QtGui.QPixmap(":/newSource/icons/reset_password_2.png"))
        self.lbl_reset_password_icon.setScaledContents(True)
        self.lbl_reset_password_icon.setObjectName("lbl_reset_password_icon")
        self.horizontalLayout_7.addWidget(self.lbl_reset_password_icon)
        self.lbl_header = QtWidgets.QLabel(parent=self.widget_header_inner_header_reset_password)
        self.lbl_header.setMinimumSize(QtCore.QSize(140, 22))
        self.lbl_header.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(1) # Was -1
        self.lbl_header.setFont(font)
        self.lbl_header.setObjectName("lbl_header")
        self.horizontalLayout_7.addWidget(self.lbl_header)
        spacerItem9 = QtWidgets.QSpacerItem(138, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.lbl_header_message = QtWidgets.QLabel(parent=self.widget_inner_header_reset_password)
        self.lbl_header_message.setGeometry(QtCore.QRect(0, 30, 501, 20))
        self.lbl_header_message.setMinimumSize(QtCore.QSize(441, 20))
        self.lbl_header_message.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(1) # Was -1
        self.lbl_header_message.setFont(font)
        self.lbl_header_message.setWordWrap(True)
        self.lbl_header_message.setObjectName("lbl_header_message")
        self.verticalLayout_7.addWidget(self.widget_inner_header_reset_password)
        self.gridLayout_3.addWidget(self.widget_header_page_reset_password, 1, 0, 1, 1)
        self.widget_reset_password_container = QtWidgets.QWidget(parent=self.page_reset_password)
        self.widget_reset_password_container.setMinimumSize(QtCore.QSize(459, 250))
        self.widget_reset_password_container.setStyleSheet("QWidget {\n"
"    background-color:#242424;\n"
"    border:1px solid #242424;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color:#f0f0f0;\n"
"    font-size:18px;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_header_message\"]{\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_email_page_reset\"]{\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_otp_message\"]{\n"
"    font-size:11px;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_otp_spam_message\"]{\n"
"    font-size:11px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border:2px solid #555555;\n"
"    border-radius:10px;\n"
"    background-color:#555555;\n"
"    color:#f0f0f0;\n"
"    padding-left:8px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border:1px solid #f0f0f0;\n"
"    border-radius:10px;\n"
"    background-color:#555555;\n"
"    background\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:#be8af9;\n"
"    color:#1b0038;\n"
"    border:2px solid #be8af9;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color:#f0f0f0;\n"
"    color:#000000;\n"
"    border:2px solid #f0f0f0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color:#808080;\n"
"    color:#000000;\n"
"    border:2px solid #808080;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_cancel_page_reset\"]{\n"
"    background-color:#555555;\n"
"    border:2px solid #555555;\n"
"    color:#f0f0f0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_cancel_page_reset\"]::hover {\n"
"    background-color:#f0f0f0;\n"
"    color:#000000;\n"
"    border:2px solid #f0f0f0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_cancel_page_reset\"]::pressed {\n"
"    background-color:#808080;\n"
"    color:#000000;\n"
"    border:2px solid #808080;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color:#f0f0f0;\n"
"}")
        self.widget_reset_password_container.setObjectName("widget_reset_password_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_reset_password_container)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_email_page_reset = QtWidgets.QLabel(parent=self.widget_reset_password_container)
        self.lbl_email_page_reset.setMinimumSize(QtCore.QSize(341, 16))
        self.lbl_email_page_reset.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbl_email_page_reset.setObjectName("lbl_email_page_reset")
        self.verticalLayout_3.addWidget(self.lbl_email_page_reset)
        self.widget_10 = QtWidgets.QWidget(parent=self.widget_reset_password_container)
        self.widget_10.setMinimumSize(QtCore.QSize(406, 40))
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lbl_email_icon_page_reset = QtWidgets.QLabel(parent=self.widget_10)
        self.lbl_email_icon_page_reset.setMinimumSize(QtCore.QSize(31, 31))
        self.lbl_email_icon_page_reset.setMaximumSize(QtCore.QSize(31, 31))
        self.lbl_email_icon_page_reset.setText("")
        self.lbl_email_icon_page_reset.setPixmap(QtGui.QPixmap(":/newSource/icons/email_2.png"))
        self.lbl_email_icon_page_reset.setScaledContents(True)
        self.lbl_email_icon_page_reset.setObjectName("lbl_email_icon_page_reset")
        self.horizontalLayout_8.addWidget(self.lbl_email_icon_page_reset)
        self.lineEdit_email_page_reset = QtWidgets.QLineEdit(parent=self.widget_10)
        self.lineEdit_email_page_reset.setMinimumSize(QtCore.QSize(351, 31))
        self.lineEdit_email_page_reset.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lineEdit_email_page_reset.setClearButtonEnabled(True)
        self.lineEdit_email_page_reset.setObjectName("lineEdit_email_page_reset")
        self.horizontalLayout_8.addWidget(self.lineEdit_email_page_reset)
        self.verticalLayout_3.addWidget(self.widget_10)
        self.lbl_otp_message = QtWidgets.QLabel(parent=self.widget_reset_password_container)
        self.lbl_otp_message.setMinimumSize(QtCore.QSize(0, 22))
        self.lbl_otp_message.setMaximumSize(QtCore.QSize(16777215, 22))
        self.lbl_otp_message.setObjectName("lbl_otp_message")
        self.verticalLayout_3.addWidget(self.lbl_otp_message)
        self.lbl_otp_spam_message = QtWidgets.QLabel(parent=self.widget_reset_password_container)
        self.lbl_otp_spam_message.setMinimumSize(QtCore.QSize(0, 22))
        self.lbl_otp_spam_message.setMaximumSize(QtCore.QSize(16777215, 22))
        self.lbl_otp_spam_message.setObjectName("lbl_otp_spam_message")
        self.verticalLayout_3.addWidget(self.lbl_otp_spam_message)
        self.widget_sub_bar_page_reset = QtWidgets.QWidget(parent=self.widget_reset_password_container)
        self.widget_sub_bar_page_reset.setMinimumSize(QtCore.QSize(406, 40))
        self.widget_sub_bar_page_reset.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_sub_bar_page_reset.setObjectName("widget_sub_bar_page_reset")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_sub_bar_page_reset)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem10 = QtWidgets.QSpacerItem(110, 19, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.btn_cancel_page_reset = QtWidgets.QPushButton(parent=self.widget_sub_bar_page_reset)
        self.btn_cancel_page_reset.setMinimumSize(QtCore.QSize(91, 31))
        self.btn_cancel_page_reset.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newSource/icons/cancel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_cancel_page_reset.setIcon(icon1)
        self.btn_cancel_page_reset.setObjectName("btn_cancel_page_reset")
        self.horizontalLayout_10.addWidget(self.btn_cancel_page_reset)
        self.btn_send_code = QtWidgets.QPushButton(parent=self.widget_sub_bar_page_reset)
        self.btn_send_code.setMinimumSize(QtCore.QSize(91, 31))
        self.btn_send_code.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newSource/icons/send_code_4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_send_code.setIcon(icon2)
        self.btn_send_code.setObjectName("btn_send_code")
        self.horizontalLayout_10.addWidget(self.btn_send_code)
        spacerItem11 = QtWidgets.QSpacerItem(111, 19, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.verticalLayout_3.addWidget(self.widget_sub_bar_page_reset)
        self.gridLayout_3.addWidget(self.widget_reset_password_container, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_reset_password)
        self.page_reset_password_step2 = QtWidgets.QWidget()
        self.page_reset_password_step2.setObjectName("page_reset_password_step2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_reset_password_step2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_header_reset_step2 = QtWidgets.QWidget(parent=self.page_reset_password_step2)
        self.widget_header_reset_step2.setMinimumSize(QtCore.QSize(411, 68))
        self.widget_header_reset_step2.setMaximumSize(QtCore.QSize(16777215, 68))
        self.widget_header_reset_step2.setStyleSheet("QLabel[objectName=\"lbl_header_reset_step2\"] {\n"
"    color:#f0f0f0;\n"
"    background-color:#191919;\n"
"    font-size:18px;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_header_message_reset_step2\"] {\n"
"    color:#f0f0f0;\n"
"    background-color:#191919;\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color:#191919;\n"
"}")
        self.widget_header_reset_step2.setObjectName("widget_header_reset_step2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_header_reset_step2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_message_reset_step2 = QtWidgets.QLabel(parent=self.widget_header_reset_step2)
        self.lbl_message_reset_step2.setObjectName("lbl_message_reset_step2")
        self.verticalLayout_4.addWidget(self.lbl_message_reset_step2)
        self.lbl_header_message_reset_step2 = QtWidgets.QLabel(parent=self.widget_header_reset_step2)
        self.lbl_header_message_reset_step2.setObjectName("lbl_header_message_reset_step2")
        self.verticalLayout_4.addWidget(self.lbl_header_message_reset_step2)
        self.verticalLayout_6.addWidget(self.widget_header_reset_step2)
        self.widget_container_reset_step2 = QtWidgets.QWidget(parent=self.page_reset_password_step2)
        self.widget_container_reset_step2.setStyleSheet("QWidget {\n"
"    background-color:#242424;\n"
"    border:1px solid #242424;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color:#f0f0f0;\n"
"    font-size:18px;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_passcode\"]{\n"
"    font-size:11px;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_new_password\"]{\n"
"    font-size:11px;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_confirm_password\"]{\n"
"    font-size:11px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border:2px solid #555555;\n"
"    border-radius:10px;\n"
"    background-color:#555555;\n"
"    color:#f0f0f0;\n"
"    padding-left:8px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border:1px solid #f0f0f0;\n"
"    border-radius:10px;\n"
"    background-color:#555555;\n"
"    background\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:#555555;\n"
"    border:2px solid #555555;\n"
"    color:#f0f0f0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color:#f0f0f0;\n"
"    color:#000000;\n"
"    border:2px solid #f0f0f0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color:#808080;\n"
"    color:#000000;\n"
"    border:2px solid #808080;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_complete\"] {\n"
"    background-color:#be8af9;\n"
"    color:#1b0038;\n"
"    border:2px solid #be8af9;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_complete\"]::hover {\n"
"    background-color:#f0f0f0;\n"
"    color:#000000;\n"
"    border:2px solid #f0f0f0;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton[objectName=\"btn_complete\"]::pressed {\n"
"    background-color:#808080;\n"
"    color:#000000;\n"
"    border:2px solid #808080;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color:#f0f0f0;\n"
"}")
        self.widget_container_reset_step2.setObjectName("widget_container_reset_step2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_container_reset_step2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_passcode = QtWidgets.QLabel(parent=self.widget_container_reset_step2)
        self.lbl_passcode.setMinimumSize(QtCore.QSize(341, 16))
        self.lbl_passcode.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbl_passcode.setObjectName("lbl_passcode")
        self.verticalLayout_5.addWidget(self.lbl_passcode)
        self.widget_passcode = QtWidgets.QWidget(parent=self.widget_container_reset_step2)
        self.widget_passcode.setMinimumSize(QtCore.QSize(406, 40))
        self.widget_passcode.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_passcode.setObjectName("widget_passcode")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_passcode)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lbl_passcode_icon = QtWidgets.QLabel(parent=self.widget_passcode)
        self.lbl_passcode_icon.setMinimumSize(QtCore.QSize(31, 31))
        self.lbl_passcode_icon.setMaximumSize(QtCore.QSize(31, 31))
        self.lbl_passcode_icon.setText("")
        self.lbl_passcode_icon.setPixmap(QtGui.QPixmap(":/newSource/icons/passcode.png"))
        self.lbl_passcode_icon.setScaledContents(True)
        self.lbl_passcode_icon.setObjectName("lbl_passcode_icon")
        self.horizontalLayout_12.addWidget(self.lbl_passcode_icon)
        self.lineEdit_passcode = QtWidgets.QLineEdit(parent=self.widget_passcode)
        self.lineEdit_passcode.setMinimumSize(QtCore.QSize(351, 31))
        self.lineEdit_passcode.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lineEdit_passcode.setClearButtonEnabled(True)
        self.lineEdit_passcode.setObjectName("lineEdit_passcode")
        self.horizontalLayout_12.addWidget(self.lineEdit_passcode)
        self.verticalLayout_5.addWidget(self.widget_passcode)
        self.lbl_new_password = QtWidgets.QLabel(parent=self.widget_container_reset_step2)
        self.lbl_new_password.setMinimumSize(QtCore.QSize(341, 16))
        self.lbl_new_password.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbl_new_password.setObjectName("lbl_new_password")
        self.verticalLayout_5.addWidget(self.lbl_new_password)
        self.widget_new_password = QtWidgets.QWidget(parent=self.widget_container_reset_step2)
        self.widget_new_password.setMinimumSize(QtCore.QSize(406, 40))
        self.widget_new_password.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_new_password.setObjectName("widget_new_password")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_new_password)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbl_password_icon_reset_step2 = QtWidgets.QLabel(parent=self.widget_new_password)
        self.lbl_password_icon_reset_step2.setMinimumSize(QtCore.QSize(31, 31))
        self.lbl_password_icon_reset_step2.setMaximumSize(QtCore.QSize(31, 31))
        self.lbl_password_icon_reset_step2.setText("")
        self.lbl_password_icon_reset_step2.setPixmap(QtGui.QPixmap(":/newSource/icons/password.png"))
        self.lbl_password_icon_reset_step2.setScaledContents(True)
        self.lbl_password_icon_reset_step2.setObjectName("lbl_password_icon_reset_step2")
        self.horizontalLayout_13.addWidget(self.lbl_password_icon_reset_step2)
        self.lineEdit_new_password = QtWidgets.QLineEdit(parent=self.widget_new_password)
        self.lineEdit_new_password.setMinimumSize(QtCore.QSize(351, 31))
        self.lineEdit_new_password.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lineEdit_new_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_new_password.setClearButtonEnabled(True)
        self.lineEdit_new_password.setObjectName("lineEdit_new_password")
        self.horizontalLayout_13.addWidget(self.lineEdit_new_password)
        self.verticalLayout_5.addWidget(self.widget_new_password)
        self.lbl_confirm_password = QtWidgets.QLabel(parent=self.widget_container_reset_step2)
        self.lbl_confirm_password.setMinimumSize(QtCore.QSize(341, 16))
        self.lbl_confirm_password.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbl_confirm_password.setObjectName("lbl_confirm_password")
        self.verticalLayout_5.addWidget(self.lbl_confirm_password)
        self.widget_confirm_password = QtWidgets.QWidget(parent=self.widget_container_reset_step2)
        self.widget_confirm_password.setMinimumSize(QtCore.QSize(406, 40))
        self.widget_confirm_password.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_confirm_password.setObjectName("widget_confirm_password")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_confirm_password)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lbl_confirm_password_icon = QtWidgets.QLabel(parent=self.widget_confirm_password)
        self.lbl_confirm_password_icon.setMinimumSize(QtCore.QSize(31, 31))
        self.lbl_confirm_password_icon.setMaximumSize(QtCore.QSize(31, 31))
        self.lbl_confirm_password_icon.setText("")
        self.lbl_confirm_password_icon.setPixmap(QtGui.QPixmap(":/newSource/icons/confirm_password.png"))
        self.lbl_confirm_password_icon.setScaledContents(True)
        self.lbl_confirm_password_icon.setObjectName("lbl_confirm_password_icon")
        self.horizontalLayout_15.addWidget(self.lbl_confirm_password_icon)
        self.lineEdit_confirm_password = QtWidgets.QLineEdit(parent=self.widget_confirm_password)
        self.lineEdit_confirm_password.setMinimumSize(QtCore.QSize(351, 31))
        self.lineEdit_confirm_password.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lineEdit_confirm_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_confirm_password.setClearButtonEnabled(True)
        self.lineEdit_confirm_password.setObjectName("lineEdit_confirm_password")
        self.horizontalLayout_15.addWidget(self.lineEdit_confirm_password)
        self.verticalLayout_5.addWidget(self.widget_confirm_password)
        self.widget_show_password = QtWidgets.QWidget(parent=self.widget_container_reset_step2)
        self.widget_show_password.setMinimumSize(QtCore.QSize(406, 40))
        self.widget_show_password.setObjectName("widget_show_password")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_show_password)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_show_password_reset_step2 = QtWidgets.QCheckBox(parent=self.widget_show_password)
        self.checkBox_show_password_reset_step2.setMinimumSize(QtCore.QSize(101, 17))
        self.checkBox_show_password_reset_step2.setObjectName("checkBox_show_password_reset_step2")
        self.horizontalLayout_11.addWidget(self.checkBox_show_password_reset_step2)
        spacerItem12 = QtWidgets.QSpacerItem(189, 19, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.verticalLayout_5.addWidget(self.widget_show_password)
        self.widget_20 = QtWidgets.QWidget(parent=self.widget_container_reset_step2)
        self.widget_20.setMinimumSize(QtCore.QSize(406, 40))
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btn_cancel_page_reset_step_2 = QtWidgets.QPushButton(parent=self.widget_20)
        self.btn_cancel_page_reset_step_2.setMinimumSize(QtCore.QSize(91, 31))
        self.btn_cancel_page_reset_step_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_cancel_page_reset_step_2.setIcon(icon1)
        self.btn_cancel_page_reset_step_2.setObjectName("btn_cancel_page_reset_step_2")
        self.horizontalLayout_16.addWidget(self.btn_cancel_page_reset_step_2)
        self.btn_back_reset_step2 = QtWidgets.QPushButton(parent=self.widget_20)
        self.btn_back_reset_step2.setMinimumSize(QtCore.QSize(91, 31))
        self.btn_back_reset_step2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newSource/icons/back.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_back_reset_step2.setIcon(icon3)
        self.btn_back_reset_step2.setObjectName("btn_back_reset_step2")
        self.horizontalLayout_16.addWidget(self.btn_back_reset_step2)
        self.btn_resend_code = QtWidgets.QPushButton(parent=self.widget_20)
        self.btn_resend_code.setMinimumSize(QtCore.QSize(91, 31))
        self.btn_resend_code.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newSource/icons/resend.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_resend_code.setIcon(icon4)
        self.btn_resend_code.setObjectName("btn_resend_code")
        self.horizontalLayout_16.addWidget(self.btn_resend_code)
        self.btn_complete = QtWidgets.QPushButton(parent=self.widget_20)
        self.btn_complete.setMinimumSize(QtCore.QSize(91, 31))
        self.btn_complete.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newSource/icons/complete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_complete.setIcon(icon5)
        self.btn_complete.setObjectName("btn_complete")
        self.horizontalLayout_16.addWidget(self.btn_complete)
        self.verticalLayout_5.addWidget(self.widget_20)
        spacerItem13 = QtWidgets.QSpacerItem(20, 154, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13)
        self.verticalLayout_6.addWidget(self.widget_container_reset_step2)
        self.stackedWidget.addWidget(self.page_reset_password_step2)
        self.page_about = QtWidgets.QWidget()
        self.page_about.setObjectName("page_about")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_about)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_container_page_about = QtWidgets.QWidget(parent=self.page_about)
        self.widget_container_page_about.setStyleSheet("QWidget {\n"
"    background-color:#242424;\n"
"    border:1px solid #242424;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color:#f0f0f0;\n"
"    font-size:18px;\n"
"}")
        self.widget_container_page_about.setObjectName("widget_container_page_about")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_container_page_about)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_profile_1 = QtWidgets.QWidget(parent=self.widget_container_page_about)
        self.widget_profile_1.setMinimumSize(QtCore.QSize(170, 0))
        self.widget_profile_1.setObjectName("widget_profile_1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_profile_1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem14 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem14, 1, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem15, 3, 1, 1, 1)
        self.lbl_profile_1_icon = QtWidgets.QLabel(parent=self.widget_profile_1)
        self.lbl_profile_1_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.lbl_profile_1_icon.setText("")
        self.lbl_profile_1_icon.setPixmap(QtGui.QPixmap(":/newSource/icons/profile_1.png"))
        self.lbl_profile_1_icon.setScaledContents(True)
        self.lbl_profile_1_icon.setObjectName("lbl_profile_1_icon")
        self.gridLayout_5.addWidget(self.lbl_profile_1_icon, 1, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem16, 1, 2, 1, 1)
        self.widget_profile_1_info = QtWidgets.QWidget(parent=self.widget_profile_1)
        self.widget_profile_1_info.setMinimumSize(QtCore.QSize(142, 92))
        self.widget_profile_1_info.setStyleSheet("QLabel {\n"
"    font-size:12px;\n"
"}")
        self.widget_profile_1_info.setObjectName("widget_profile_1_info")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_profile_1_info)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lbl_profile_1_name = QtWidgets.QLabel(parent=self.widget_profile_1_info)
        self.lbl_profile_1_name.setMinimumSize(QtCore.QSize(133, 34))
        self.lbl_profile_1_name.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lbl_profile_1_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_profile_1_name.setObjectName("lbl_profile_1_name")
        self.verticalLayout_9.addWidget(self.lbl_profile_1_name)
        self.widget_profile_1_no = QtWidgets.QWidget(parent=self.widget_profile_1_info)
        self.widget_profile_1_no.setMinimumSize(QtCore.QSize(133, 34))
        self.widget_profile_1_no.setObjectName("widget_profile_1_no")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_profile_1_no)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lbl_profile_1_no_header = QtWidgets.QLabel(parent=self.widget_profile_1_no)
        self.lbl_profile_1_no_header.setMinimumSize(QtCore.QSize(38, 0))
        self.lbl_profile_1_no_header.setMaximumSize(QtCore.QSize(40, 40))
        self.lbl_profile_1_no_header.setObjectName("lbl_profile_1_no_header")
        self.horizontalLayout_14.addWidget(self.lbl_profile_1_no_header)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem17)
        self.lbl_profile_1_no = QtWidgets.QLabel(parent=self.widget_profile_1_no)
        self.lbl_profile_1_no.setMinimumSize(QtCore.QSize(72, 16))
        self.lbl_profile_1_no.setWordWrap(True)
        self.lbl_profile_1_no.setObjectName("lbl_profile_1_no")
        self.horizontalLayout_14.addWidget(self.lbl_profile_1_no)
        self.verticalLayout_9.addWidget(self.widget_profile_1_no)
        self.gridLayout_5.addWidget(self.widget_profile_1_info, 2, 0, 1, 3)
        spacerItem18 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem18, 0, 1, 1, 1)
        self.horizontalLayout_9.addWidget(self.widget_profile_1)
        self.widget_profile_2 = QtWidgets.QWidget(parent=self.widget_container_page_about)
        self.widget_profile_2.setMinimumSize(QtCore.QSize(170, 0))
        self.widget_profile_2.setStyleSheet("QLabel {\n"
"    font-size:12px;\n"
"}")
        self.widget_profile_2.setObjectName("widget_profile_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_profile_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem19 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem19, 3, 1, 1, 1)
        self.lbl_profile_2_icon = QtWidgets.QLabel(parent=self.widget_profile_2)
        self.lbl_profile_2_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.lbl_profile_2_icon.setText("")
        self.lbl_profile_2_icon.setPixmap(QtGui.QPixmap(":/newSource/icons/profile_1.png"))
        self.lbl_profile_2_icon.setScaledContents(True)
        self.lbl_profile_2_icon.setObjectName("lbl_profile_2_icon")
        self.gridLayout_6.addWidget(self.lbl_profile_2_icon, 1, 1, 1, 1)
        self.widget_profile_2_info = QtWidgets.QWidget(parent=self.widget_profile_2)
        self.widget_profile_2_info.setMinimumSize(QtCore.QSize(142, 92))
        self.widget_profile_2_info.setStyleSheet("QLabel {\n"
"    font-size:12px;\n"
"}")
        self.widget_profile_2_info.setObjectName("widget_profile_2_info")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_profile_2_info)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lbl_profile_2_name = QtWidgets.QLabel(parent=self.widget_profile_2_info)
        self.lbl_profile_2_name.setMinimumSize(QtCore.QSize(133, 34))
        self.lbl_profile_2_name.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lbl_profile_2_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_profile_2_name.setObjectName("lbl_profile_2_name")
        self.verticalLayout_10.addWidget(self.lbl_profile_2_name)
        self.widget_profile_2_no = QtWidgets.QWidget(parent=self.widget_profile_2_info)
        self.widget_profile_2_no.setMinimumSize(QtCore.QSize(133, 34))
        self.widget_profile_2_no.setObjectName("widget_profile_2_no")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_profile_2_no)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lbl_profile_2_no_header = QtWidgets.QLabel(parent=self.widget_profile_2_no)
        self.lbl_profile_2_no_header.setMinimumSize(QtCore.QSize(38, 0))
        self.lbl_profile_2_no_header.setMaximumSize(QtCore.QSize(40, 40))
        self.lbl_profile_2_no_header.setObjectName("lbl_profile_2_no_header")
        self.horizontalLayout_17.addWidget(self.lbl_profile_2_no_header)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem20)
        self.lbl_profile_2_no = QtWidgets.QLabel(parent=self.widget_profile_2_no)
        self.lbl_profile_2_no.setMinimumSize(QtCore.QSize(72, 16))
        self.lbl_profile_2_no.setWordWrap(True)
        self.lbl_profile_2_no.setObjectName("lbl_profile_2_no")
        self.horizontalLayout_17.addWidget(self.lbl_profile_2_no)
        self.verticalLayout_10.addWidget(self.widget_profile_2_no)
        self.gridLayout_6.addWidget(self.widget_profile_2_info, 2, 0, 1, 3)
        spacerItem21 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem21, 1, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem22, 1, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem23, 0, 1, 1, 1)
        self.horizontalLayout_9.addWidget(self.widget_profile_2)
        self.widget_profile_3 = QtWidgets.QWidget(parent=self.widget_container_page_about)
        self.widget_profile_3.setMinimumSize(QtCore.QSize(170, 0))
        self.widget_profile_3.setStyleSheet("QLabel {\n"
"    font-size:12px;\n"
"}")
        self.widget_profile_3.setObjectName("widget_profile_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_profile_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_profile_3_info = QtWidgets.QWidget(parent=self.widget_profile_3)
        self.widget_profile_3_info.setMinimumSize(QtCore.QSize(142, 92))
        self.widget_profile_3_info.setStyleSheet("QLabel {\n"
"    font-size:12px;\n"
"}")
        self.widget_profile_3_info.setObjectName("widget_profile_3_info")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_profile_3_info)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lbl_profile_3_name = QtWidgets.QLabel(parent=self.widget_profile_3_info)
        self.lbl_profile_3_name.setMinimumSize(QtCore.QSize(133, 34))
        self.lbl_profile_3_name.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lbl_profile_3_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_profile_3_name.setObjectName("lbl_profile_3_name")
        self.verticalLayout_11.addWidget(self.lbl_profile_3_name)
        self.widget_profile_3_no = QtWidgets.QWidget(parent=self.widget_profile_3_info)
        self.widget_profile_3_no.setMinimumSize(QtCore.QSize(133, 34))
        self.widget_profile_3_no.setObjectName("widget_profile_3_no")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_profile_3_no)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lbl_profile_3_no_header = QtWidgets.QLabel(parent=self.widget_profile_3_no)
        self.lbl_profile_3_no_header.setMinimumSize(QtCore.QSize(38, 0))
        self.lbl_profile_3_no_header.setMaximumSize(QtCore.QSize(40, 40))
        self.lbl_profile_3_no_header.setObjectName("lbl_profile_3_no_header")
        self.horizontalLayout_18.addWidget(self.lbl_profile_3_no_header)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem24)
        self.lbl_profile_3_no = QtWidgets.QLabel(parent=self.widget_profile_3_no)
        self.lbl_profile_3_no.setMinimumSize(QtCore.QSize(72, 16))
        self.lbl_profile_3_no.setWordWrap(True)
        self.lbl_profile_3_no.setObjectName("lbl_profile_3_no")
        self.horizontalLayout_18.addWidget(self.lbl_profile_3_no)
        self.verticalLayout_11.addWidget(self.widget_profile_3_no)
        self.gridLayout_7.addWidget(self.widget_profile_3_info, 2, 0, 1, 3)
        spacerItem25 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem25, 3, 1, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem26, 1, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem27, 1, 2, 1, 1)
        self.lbl_profile_3_icon = QtWidgets.QLabel(parent=self.widget_profile_3)
        self.lbl_profile_3_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.lbl_profile_3_icon.setText("")
        self.lbl_profile_3_icon.setPixmap(QtGui.QPixmap(":/newSource/icons/profile_1.png"))
        self.lbl_profile_3_icon.setScaledContents(True)
        self.lbl_profile_3_icon.setObjectName("lbl_profile_3_icon")
        self.gridLayout_7.addWidget(self.lbl_profile_3_icon, 1, 1, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem28, 0, 1, 1, 1)
        self.horizontalLayout_9.addWidget(self.widget_profile_3)
        self.gridLayout_4.addWidget(self.widget_container_page_about, 1, 0, 1, 1)
        self.widget_header_page_about = QtWidgets.QWidget(parent=self.page_about)
        self.widget_header_page_about.setMinimumSize(QtCore.QSize(411, 68))
        self.widget_header_page_about.setMaximumSize(QtCore.QSize(16777215, 68))
        self.widget_header_page_about.setStyleSheet("QLabel[objectName=\"lbl_header_about\"] {\n"
"    color:#f0f0f0;\n"
"    background-color:#191919;\n"
"    font-size:18px;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QLabel[objectName=\"lbl_header_message_about\"] {\n"
"    color:#f0f0f0;\n"
"    background-color:#191919;\n"
"    font-size:12px;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color:#191919;\n"
"}")
        self.widget_header_page_about.setObjectName("widget_header_page_about")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_header_page_about)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem29 = QtWidgets.QSpacerItem(181, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem29)
        self.lbl_about_icon = QtWidgets.QLabel(parent=self.widget_header_page_about)
        self.lbl_about_icon.setMinimumSize(QtCore.QSize(40, 28))
        self.lbl_about_icon.setMaximumSize(QtCore.QSize(50, 30))
        self.lbl_about_icon.setText("")
        self.lbl_about_icon.setPixmap(QtGui.QPixmap(":/newSource/icons/about.png"))
        self.lbl_about_icon.setScaledContents(True)
        self.lbl_about_icon.setObjectName("lbl_about_icon")
        self.horizontalLayout_19.addWidget(self.lbl_about_icon)
        self.lbl_header_about = QtWidgets.QLabel(parent=self.widget_header_page_about)
        self.lbl_header_about.setMinimumSize(QtCore.QSize(61, 26))
        self.lbl_header_about.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(1) # Was -1
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header_about.setFont(font)
        self.lbl_header_about.setObjectName("lbl_header_about")
        self.horizontalLayout_19.addWidget(self.lbl_header_about)
        spacerItem30 = QtWidgets.QSpacerItem(180, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem30)
        self.gridLayout_4.addWidget(self.widget_header_page_about, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_about)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuForm = QtWidgets.QMenu(parent=self.menuBar)
        self.menuForm.setObjectName("menuForm")
        self.menu_Check_Connection = QtWidgets.QMenu(parent=self.menuForm)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newSource/icons/check_connection.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_Check_Connection.setIcon(icon6)
        self.menu_Check_Connection.setObjectName("menu_Check_Connection")
        MainWindow.setMenuBar(self.menuBar)
        self.action3_sec = QtGui.QAction(parent=MainWindow)
        self.action3_sec.setObjectName("action3_sec")
        self.action5_sec = QtGui.QAction(parent=MainWindow)
        self.action5_sec.setObjectName("action5_sec")
        self.action10_sec = QtGui.QAction(parent=MainWindow)
        self.action10_sec.setObjectName("action10_sec")
        self.action30_sec = QtGui.QAction(parent=MainWindow)
        self.action30_sec.setObjectName("action30_sec")
        self.action60_sec = QtGui.QAction(parent=MainWindow)
        self.action60_sec.setObjectName("action60_sec")
        self.action90_sec = QtGui.QAction(parent=MainWindow)
        self.action90_sec.setObjectName("action90_sec")
        self.action120_sec = QtGui.QAction(parent=MainWindow)
        self.action120_sec.setObjectName("action120_sec")
        self.actionNever = QtGui.QAction(parent=MainWindow)
        self.actionNever.setObjectName("actionNever")
        self.action_Clear_All = QtGui.QAction(parent=MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newSource/icons/clear_all.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.action_Clear_All.setIcon(icon7)
        self.action_Clear_All.setObjectName("action_Clear_All")
        self.action_Refresh_Connection = QtGui.QAction(parent=MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newSource/icons/reconnect.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.action_Refresh_Connection.setIcon(icon8)
        self.action_Refresh_Connection.setObjectName("action_Refresh_Connection")
        self.action_Restart = QtGui.QAction(parent=MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newSource/icons/restart.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.action_Restart.setIcon(icon9)
        self.action_Restart.setObjectName("action_Restart")
        self.action_3_sec = QtGui.QAction(parent=MainWindow)
        self.action_3_sec.setCheckable(True)
        self.action_3_sec.setObjectName("action_3_sec")
        self.action_5_sec = QtGui.QAction(parent=MainWindow)
        self.action_5_sec.setCheckable(True)
        self.action_5_sec.setChecked(True)
        self.action_5_sec.setObjectName("action_5_sec")
        self.action_10_sec = QtGui.QAction(parent=MainWindow)
        self.action_10_sec.setCheckable(True)
        self.action_10_sec.setObjectName("action_10_sec")
        self.action_30_sec = QtGui.QAction(parent=MainWindow)
        self.action_30_sec.setCheckable(True)
        self.action_30_sec.setObjectName("action_30_sec")
        self.action_60_sec = QtGui.QAction(parent=MainWindow)
        self.action_60_sec.setCheckable(True)
        self.action_60_sec.setObjectName("action_60_sec")
        self.action_90_sec = QtGui.QAction(parent=MainWindow)
        self.action_90_sec.setCheckable(True)
        self.action_90_sec.setObjectName("action_90_sec")
        self.action_120_sec = QtGui.QAction(parent=MainWindow)
        self.action_120_sec.setCheckable(True)
        self.action_120_sec.setObjectName("action_120_sec")
        self.action_Never = QtGui.QAction(parent=MainWindow)
        self.action_Never.setCheckable(True)
        self.action_Never.setObjectName("action_Never")
        self.menu_Check_Connection.addAction(self.action_3_sec)
        self.menu_Check_Connection.addAction(self.action_5_sec)
        self.menu_Check_Connection.addAction(self.action_10_sec)
        self.menu_Check_Connection.addAction(self.action_30_sec)
        self.menu_Check_Connection.addAction(self.action_60_sec)
        self.menu_Check_Connection.addAction(self.action_90_sec)
        self.menu_Check_Connection.addAction(self.action_120_sec)
        self.menu_Check_Connection.addSeparator()
        self.menu_Check_Connection.addAction(self.action_Never)
        self.menuForm.addAction(self.action_Clear_All)
        self.menuForm.addAction(self.action_Refresh_Connection)
        self.menuForm.addAction(self.menu_Check_Connection.menuAction())
        self.menuForm.addSeparator()
        self.menuForm.addAction(self.action_Restart)
        self.menuBar.addAction(self.menuForm.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Human Resources Management APP - Login"))
        self.lbl_connection_icon.setToolTip(_translate("MainWindow", "Status of database connection"))
        self.lbl_connection_status.setToolTip(_translate("MainWindow", "Status of database connection"))
        self.lbl_connection_status.setText(_translate("MainWindow", "Not Connected"))
        self.lbl_contact_msg.setText(_translate("MainWindow", "For contact and developer information"))
        self.btn_contact_back.setToolTip(_translate("MainWindow", "Click to reset your password"))
        self.btn_contact_back.setText(_translate("MainWindow", "Click here!"))
        self.lbl_welcome.setText(_translate("MainWindow", "Welcome Back!"))
        self.lbl_welcome_msg.setText(_translate("MainWindow", "Log into your account in order to proceed"))
        self.lbl_login.setText(_translate("MainWindow", "Login"))
        self.lbl_mail_address_login_page.setText(_translate("MainWindow", "Mail Address:"))
        self.lineEdit_email_page_login.setPlaceholderText(_translate("MainWindow", "Type your mail address"))
        self.lbl_password_login_page.setText(_translate("MainWindow", "Password:"))
        self.lineEdit_password_page_login.setPlaceholderText(_translate("MainWindow", "Type your password"))
        self.checkBox_show_password_page_login.setText(_translate("MainWindow", "Show Password"))
        self.btn_login.setText(_translate("MainWindow", "Log In"))
        self.lbl_forgot_password.setText(_translate("MainWindow", "Forgot your password?"))
        self.btn_forgot_password.setToolTip(_translate("MainWindow", "Click to reset your password"))
        self.btn_forgot_password.setText(_translate("MainWindow", "Click here!"))
        self.lbl_header.setText(_translate("MainWindow", "Reset Password"))
        self.lbl_header_message.setText(_translate("MainWindow", "You can reset your password using your mail address, or you can contact your IT manager."))
        self.lbl_email_page_reset.setText(_translate("MainWindow", "Mail Address:"))
        self.lineEdit_email_page_reset.setToolTip(_translate("MainWindow", "Your e-mail address registered in the system"))
        self.lineEdit_email_page_reset.setPlaceholderText(_translate("MainWindow", "Type your mail address"))
        self.lbl_otp_message.setText(_translate("MainWindow", "We will send a one-time password to the email address you specified."))
        self.lbl_otp_spam_message.setText(_translate("MainWindow", "You may have to check your spam folder."))
        self.btn_cancel_page_reset.setToolTip(_translate("MainWindow", "Turn back to login screen"))
        self.btn_cancel_page_reset.setText(_translate("MainWindow", "Cancel"))
        self.btn_send_code.setToolTip(_translate("MainWindow", "Continue with the process"))
        self.btn_send_code.setText(_translate("MainWindow", "Send Code"))
        self.lbl_message_reset_step2.setText(_translate("MainWindow", "Almost Done,"))
        self.lbl_header_message_reset_step2.setText(_translate("MainWindow", "Provide the one-time password we sent you and a new log in password"))
        self.lbl_passcode.setText(_translate("MainWindow", "Passcode:"))
        self.lineEdit_passcode.setPlaceholderText(_translate("MainWindow", "Type the one-time password that we sent you"))
        self.lbl_new_password.setText(_translate("MainWindow", "New Password:"))
        self.lineEdit_new_password.setPlaceholderText(_translate("MainWindow", "Type your new password"))
        self.lbl_confirm_password.setText(_translate("MainWindow", "Confirm Password:"))
        self.lineEdit_confirm_password.setPlaceholderText(_translate("MainWindow", "Confirm your new password"))
        self.checkBox_show_password_reset_step2.setText(_translate("MainWindow", "Show Password"))
        self.btn_cancel_page_reset_step_2.setToolTip(_translate("MainWindow", "Turn back to login screen"))
        self.btn_cancel_page_reset_step_2.setText(_translate("MainWindow", "Cancel"))
        self.btn_back_reset_step2.setToolTip(_translate("MainWindow", "Turn back to arrange your email address"))
        self.btn_back_reset_step2.setText(_translate("MainWindow", "Back"))
        self.btn_resend_code.setToolTip(_translate("MainWindow", "Click to get a new passcode"))
        self.btn_resend_code.setText(_translate("MainWindow", "Resend Code"))
        self.btn_complete.setToolTip(_translate("MainWindow", "Change the password"))
        self.btn_complete.setText(_translate("MainWindow", "Complete"))
        self.lbl_profile_1_icon.setToolTip(_translate("MainWindow", "Fevzi FİDAN"))
        self.lbl_profile_1_name.setText(_translate("MainWindow", "Fevzi FİDAN"))
        self.lbl_profile_1_no_header.setToolTip(_translate("MainWindow", "Student Number"))
        self.lbl_profile_1_no_header.setText(_translate("MainWindow", "S.No:"))
        self.lbl_profile_1_no.setText(_translate("MainWindow", "NULL"))
        self.lbl_profile_2_icon.setToolTip(_translate("MainWindow", "Hikmet ÇATAK"))
        self.lbl_profile_2_name.setText(_translate("MainWindow", "Hikmet ÇATAK"))
        self.lbl_profile_2_no_header.setToolTip(_translate("MainWindow", "Student Number"))
        self.lbl_profile_2_no_header.setText(_translate("MainWindow", "S.No:"))
        self.lbl_profile_2_no.setText(_translate("MainWindow", "NULL"))
        self.lbl_profile_3_name.setText(_translate("MainWindow", "Ömer Faruk AZİLİ"))
        self.lbl_profile_3_no_header.setToolTip(_translate("MainWindow", "Student Number"))
        self.lbl_profile_3_no_header.setText(_translate("MainWindow", "S.No:"))
        self.lbl_profile_3_no.setText(_translate("MainWindow", "NULL"))
        self.lbl_profile_3_icon.setToolTip(_translate("MainWindow", "Ömer Faruk AZİLİ"))
        self.lbl_header_about.setText(_translate("MainWindow", "About"))
        self.menuForm.setTitle(_translate("MainWindow", "Application"))
        self.menu_Check_Connection.setTitle(_translate("MainWindow", "Check Connection"))
        self.action3_sec.setText(_translate("MainWindow", "3 sec"))
        self.action5_sec.setText(_translate("MainWindow", "5 sec"))
        self.action10_sec.setText(_translate("MainWindow", "10 sec"))
        self.action30_sec.setText(_translate("MainWindow", "30 sec"))
        self.action60_sec.setText(_translate("MainWindow", "60 sec"))
        self.action90_sec.setText(_translate("MainWindow", "90 sec"))
        self.action120_sec.setText(_translate("MainWindow", "120 sec"))
        self.actionNever.setText(_translate("MainWindow", "Never"))
        self.action_Clear_All.setText(_translate("MainWindow", "Clear All"))
        self.action_Refresh_Connection.setText(_translate("MainWindow", "Try to Reconnect"))
        self.action_Restart.setText(_translate("MainWindow", "Restart"))
        self.action_3_sec.setText(_translate("MainWindow", "3 sec"))
        self.action_5_sec.setText(_translate("MainWindow", "5 sec"))
        self.action_10_sec.setText(_translate("MainWindow", "10 sec"))
        self.action_30_sec.setText(_translate("MainWindow", "30 sec"))
        self.action_60_sec.setText(_translate("MainWindow", "60 sec"))
        self.action_90_sec.setText(_translate("MainWindow", "90 sec"))
        self.action_120_sec.setText(_translate("MainWindow", "120 sec"))
        self.action_Never.setText(_translate("MainWindow", "Never"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
